### ISSUE TITLE
你好,请问你之前那个本地显示正常,github显示不正常是怎么解决的呢?

### ISSUE THREAD

**Issue by zhanglei518** [StoneRen/stoneren.github.io#1]

**Comment by StoneRen** [comment]
@zhanglei518 能把问题详细说一下吗? 没明白你说的什么意思

**Comment by zhanglei518** [comment]
谢谢，那个问题给我已经解决啦，想了解一下你的相册是抓取的ins的资源么还是七牛呢


祝好。
在2017年09月15日 12:25，StoneRen 写道：

@zhanglei518 能把问题详细说一下吗? 没明白你说的什么意思

**Comment by StoneRen** [comment]
@zhanglei518  用的七牛的资源. 可以看一下我相册的[源码](https://github.com/StoneRen/stoneren.github.io/blob/master/photo/photo.js)
因为github只能放纯静态的文件,不想搭服务器去转发ins的请求.所以就自己用了七牛.

七牛国内的访问速度都还是很快的.

改天我会放一篇我改造相册的文章.中间确实碰到很多坑

**Comment by StoneRen** [comment]
已经放出相册源码解析的[文章](https://jsfun.info/archive/photo%E9%A2%91%E9%81%93%E6%96%B0%E4%B8%8A%E5%88%86%E9%A1%B5%E5%8A%9F%E8%83%BD/)
